"""Sync WooCommerce sitemap (+ REST API) into the bridge cache and Rasa lookup tables.

Usage:
    python -m bridge.sync                 # sitemap + API + crawl pages + lookups
    python -m bridge.sync --no-crawl      # skip page crawl (fast product refresh)
    python -m bridge.sync --no-api        # sitemap only (no API keys needed)

After a sync that changed product names, retrain Rasa so NLU picks up the new
lookup tables (`docker compose run --rm rasa-train`). Product data, prices and page
answers are read live by the action server and need no retraining.
"""
import argparse
import json
import logging
import sys
import time
from pathlib import Path

from . import config
from .catalog import Catalog
from .page_index import PageIndex
from .sitemap import SitemapReader, summarize
from .store import CATALOG_FILE, PAGES_FILE
from .woo_client import WooClient

log = logging.getLogger("bridge.sync")

LOOKUP_HEADER = (
    "# AUTO-GENERATED by `python -m bridge.sync` from your WooCommerce store.\n"
    "# Do not edit by hand - changes are overwritten on the next sync.\n"
)


def write_lookups(lookups: dict, path: Path) -> bool:
    """Write Rasa NLU lookup tables. Returns True if the file content changed."""
    lines = [LOOKUP_HEADER, 'version: "3.1"', "nlu:"]
    for name, values in lookups.items():
        if not values:
            values = [f"example {name.replace('_', ' ')}"]  # Rasa rejects empty lookups
        lines.append(f"- lookup: {name}")
        lines.append("  examples: |")
        for v in values:
            lines.append(f"    - {v}")
    content = "\n".join(lines) + "\n"
    old = path.read_text() if path.exists() else ""
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def run(no_api: bool = False, no_crawl: bool = False) -> dict:
    t0 = time.time()
    if not config.WC_URL and not config.SITEMAP_URL:
        raise SystemExit("Set WC_URL (and optionally SITEMAP_URL) in .env first.")

    reader = SitemapReader()
    sitemap_url = reader.discover(config.WC_URL or config.SITEMAP_URL)
    entries = reader.read(sitemap_url)
    if not entries:
        raise SystemExit(f"Sitemap {sitemap_url} returned no URLs.")

    woo = None
    if not no_api:
        if config.woo_api_configured():
            woo = WooClient()
        else:
            log.warning("WooCommerce API keys not set - building catalogue from sitemap only.")

    catalog = Catalog.build(entries, woo)
    config.CACHE_DIR.mkdir(parents=True, exist_ok=True)
    catalog.save(config.CACHE_DIR / CATALOG_FILE)
    (config.CACHE_DIR / "sitemap.json").write_text(json.dumps([e.to_dict() for e in entries], indent=1))

    pages_count = None
    if not no_crawl:
        index = PageIndex.crawl(entries)
        index.save(config.CACHE_DIR / PAGES_FILE)
        pages_count = len(index.chunks)

    changed = write_lookups(catalog.lookup_names(), config.LOOKUP_FILE)
    report = {
        "sitemap": sitemap_url,
        "urls": summarize(entries),
        "products": len(catalog.products),
        "categories": len(catalog.categories),
        "page_chunks": pages_count,
        "lookups_changed": changed,
        "seconds": round(time.time() - t0, 1),
    }
    (config.CACHE_DIR / "last_sync.json").write_text(json.dumps(report, indent=1))
    return report


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--no-api", action="store_true", help="do not call the WooCommerce REST API")
    p.add_argument("--no-crawl", action="store_true", help="do not crawl page/post content")
    p.add_argument("-v", "--verbose", action="store_true")
    a = p.parse_args(argv)
    logging.basicConfig(level=logging.DEBUG if a.verbose else logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    report = run(no_api=a.no_api, no_crawl=a.no_crawl)
    print(json.dumps(report, indent=2))
    if report["lookups_changed"]:
        print("\nLookup tables changed -> retrain Rasa:  docker compose run --rm rasa-train", file=sys.stderr)


if __name__ == "__main__":
    main()
